/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const path = require("node:path")
const { readFileSync } = require("node:fs")

const generateBars = () => {
  /** @type {import("./src/docs.json")} */
  const docs = JSON.parse(readFileSync("./src/docs.json").toString())
  const bars = docs.map((doc) => {
    const name = path.basename(doc.path)
    /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
    const entry = {
      [name]: [ {type: 'autogenerated', dirName: name}, ]
    }

    return entry
  }).reduce((acc, doc) => ({ ...acc, ...doc }), {})
  return bars
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  ...generateBars(),

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
